version: '3.8'

networks:
  my_network:  # 네트워크 정의
    driver: bridge

services:
  app:
    build: .
    container_name: star-info-api-container_compose
    ports:
      - "5555:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - FLASK_APP=run.py  # 추가: Flask 애플리케이션 설정
      - CACHE_REDIS_HOST=redis_container  # Redis 서비스 컨테이너 이름을 호스트로 사용
      - CACHE_REDIS_PORT=6379
    volumes:
      - ./config.yml:/app/config.yml  # config.yml 파일을 컨테이너에 마운트
    depends_on:
      mysql_db:
        condition: service_healthy
      redis_container:  # Redis 서비스에 의존
        condition: service_healthy
    networks:
      - my_network
    restart: always

  mysql_db:
    image: mariadb:10.4
    container_name: mysql_container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"  # 비밀번호는 문자열로 지정
      MYSQL_DATABASE: STAR_INFO_API_DB
    volumes:
      - mysql_data:/var/lib/mysql  # 데이터베이스 데이터를 유지하기 위한 볼륨 추가
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d  # 초기화 스크립트 마운트
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234" ]
      interval: 10s
      retries: 3
    networks:
      - my_network

  redis_container:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - my_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

volumes:
  mysql_data:  # 데이터 영속성을 위한 볼륨 선언
