"""Initial migration for raw data

Revision ID: 2b188e060f1d
Revises: 
Create Date: 2024-10-25 05:34:44.716098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b188e060f1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet_raw_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('planet_name', sa.String(length=50), nullable=False),
    sa.Column('reg_date', sa.Date(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('s_o_t', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pluto_2026_raw_data')
    op.drop_table('saturn_2025_raw_data')
    op.drop_table('neptune_2024_raw_data')
    op.drop_table('saturn_2024_raw_data')
    op.drop_table('mercury_2025_raw_data')
    op.drop_table('mercury_2027_raw_data')
    op.drop_table('saturn_2027_raw_data')
    op.drop_table('mercury_2024_raw_data')
    op.drop_table('jupiter_2026_raw_data')
    op.drop_table('neptune_2026_raw_data')
    op.drop_table('uranus_2026_raw_data')
    op.drop_table('pluto_2027_raw_data')
    op.drop_table('venus_2026_raw_data')
    op.drop_table('mercury_2026_raw_data')
    op.drop_table('pluto_2025_raw_data')
    op.drop_table('uranus_2027_raw_data')
    op.drop_table('jupiter_2027_raw_data')
    op.drop_table('pluto_2024_raw_data')
    op.drop_table('neptune_2027_raw_data')
    op.drop_table('mars_2024_raw_data')
    op.drop_table('mars_2026_raw_data')
    op.drop_table('saturn_2026_raw_data')
    op.drop_table('neptune_2025_raw_data')
    op.drop_table('mars_2025_raw_data')
    op.drop_table('venus_2024_raw_data')
    op.drop_table('jupiter_2025_raw_data')
    op.drop_table('mars_2027_raw_data')
    op.drop_table('uranus_2024_raw_data')
    op.drop_table('uranus_2025_raw_data')
    op.drop_table('venus_2025_raw_data')
    op.drop_table('jupiter_2024_raw_data')
    op.drop_table('venus_2027_raw_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venus_2027_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('jupiter_2024_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('venus_2025_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('uranus_2025_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('uranus_2024_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('mars_2027_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('jupiter_2025_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('venus_2024_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('mars_2025_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('neptune_2025_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('saturn_2026_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('mars_2026_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('mars_2024_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('neptune_2027_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('pluto_2024_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('jupiter_2027_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('uranus_2027_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('pluto_2025_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('mercury_2026_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('venus_2026_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('pluto_2027_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('uranus_2026_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('neptune_2026_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('jupiter_2026_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('mercury_2024_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('saturn_2027_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('mercury_2027_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('mercury_2025_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('saturn_2024_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('neptune_2024_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('saturn_2025_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('pluto_2026_raw_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('planet_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reg_date', sa.DATE(), nullable=False),
    sa.Column('distance', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('s_o_t', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('planet_raw_data')
    # ### end Alembic commands ###
